/**:
  ros__parameters:
    confWithRos: false
    odometry:
      # Enable ROS odometry messages.
      enable: true
      use2D: true
      # Publish odometry transforms.
      publishTf: false
      # Odometry frame IDs.
      odomFrameId: odom
      baseFrameId: base_link
      initFrameId: map
      waitForDatum: true
      # datum: [-31.980724295, 115.815946083 , 0.0 ] # flipped
      #datum: [-31.97996317, 115.81716800, 0.0] #cricket building south corner
      # datum: [-31.596454, 115.668110, 0.0]  #Flying Fox Park 
      datum: [-31.9794384, 115.8160607, 0.0]  # RTK Box

    uartConf:
      portName: /dev/ttyUSB0
      # portName: /dev/ttySBG
      baudRate: 115200 #460800 #115200 921600

      # Port Id
      # 0 PORT_A: Main communication interface. Full duplex.
      # 1 PORT_B: Auxiliary input interface for RTCM
      # 2 PORT_C: Auxiliary communication interface. Full duplex.
      # 3 PORT_D: Auxiliary input interface
      # 4 PORT_E: Auxiliary input/output interface
      portID: 0

    sensorParameters:
      initLat: -31.9794384
      initLong: 115.8160607
      initAlt: 20.0
      year: 2023
      month: Jul
      day: 6

      # Montion profile ID
      # 1 GENERAL_PURPOSE Should be used as a default when other profiles do not apply
      # 2 AUTOMOTIVE      Dedicated to car applications
      # 3 MARINE          Used in marine and underwater applications
      # 4 AIRPLANE        For fixed wings aircraft
      # 5 HELICOPTER      For rotary wing aircraft
      motionProfile: 2

    rtcm:
      subscribe: true
      namespace: ""
      topic_name: "rtcm"         # default

    imuAlignementLeverArm:
      # IMU X axis direction in vehicle frame
      # 0 ALIGNMENT_FORWARD   IMU Axis is turned in vehicle's forward direction
      # 1 ALIGNMENT_BACKWARD  IMU Axis is turned in vehicle's backward direction
      # 2 ALIGNMENT_LEFT      IMU Axis is turned in vehicle's left direction
      # 3 ALIGNMENT_RIGHT     IMU Axis is turned in vehicle's right direction
      # 4 ALIGNMENT_U1P        IMU Axis is turned in vehicle's up direction
      # 5 ALIGNMENT_DOWN      IMU Axis is turned in vehicle's down direction
      axisDirectionX: 0
      # IMU Y axis direction in vehicle frame
      axisDirectionY: 2 #2

      # Residual error after axis alignment rad
      misRoll: 0.0
      misPitch: 0.0
      misYaw: 0.0

      # Primary lever arm in IMU axis (once IMU alignment is applied) m
      leverArmX: 0.0
      leverArmY: 0.0
      leverArmZ: 2.15

    # AIDING_ASSIGNMENT
    # Note: GNSS1 module configuration can only be set to an external port on Ellipse-E version.
    # Ellipse-N users must set this module to MODULE_INTERNAL. On the other hand, rtcmModule is only
    # available for Ellipse-N users. This module must be set to MODULE_DISABLED for other users.
    aidingAssignment:
      # GNSS module port assignment:
      # 5 Module is connected internally
      gnss1ModulePortAssignment: 5
      # GNSS module sync assignment:
      # 0 Module is disabled
      # 5 Synchronization is internal
      gnss1ModuleSyncAssignment: 0
      # RTCM input port assignment for Ellipse-N DGPS
      rtcmPortAssignment: 1 #255

      # Odometer module pin assignment
      # 0 Odometer is disabled
      odometerPinAssignment: 0

    magnetometer:
      # Magnetometer model ID
      # 201 Should be used in most applications
      # 202 Should be used in disturbed magnetic environment
      magnetometerModel: 202
      # Magnetometer rejection mode
      # 0 Measurement is not taken into account
      # 1 Measurement is rejected if inconsistent with current estimate (depending on error model)
      # 2 Measurement is always accepted
      magnetometerRejectMode: 0

      # Theses parameters are only used for a calibration run
      calibration:
        # 1 2D Tell the device that the magnetic calibration will be performed with limited motions.
        mode: 1

        # 0 LOW_BW Use this parameter in case of strong magnetic noise during calibration.
        #     Motion during calibration is then limited to slow rotations.
        # 1 MEDIUM_BW Tell the device that medium dynamics will be observed during the magnetic calibration process.
        #     It can be used in case of medium magnetic noise during calibration process. Medium dynamics are used during calibration.
        # 2 HIGH_BW This parameter is suitable to most applications. It can be used when the dynamics during calibration are relatively high.
        bandwidth: 2

    # GNSS configuration
    # Note: Secondary level arms should only be considered in case of dual antenna GNSS receiver. It can be left to 0 otherwise.
    gnss:
      # Gnss Model Id
      # 107 Used on Ellipse-D by default
      gnss_model_id: 107

      #GNSS primary antenna lever arm in IMU X axis (m)
      primaryLeverArmX: 1.35 #1.560
      primaryLeverArmY: 0.250 #0.040
      primaryLeverArmZ: 0.0
      primaryLeverPrecise: false

      #GNSS secondary antenna lever arm in IMU X axis (m)
      secondaryLeverArmX: -1.650 #-1.380
      secondaryLeverArmY: 0.290 #0.040
      secondaryLeverArmZ: 0.0

      # Secondary antenna operating mode.
      # 3 The GNSS dual antenna information will be used and we have a rough guess for the secondary lever arm.
      # 4 The GNSS dual antenna information will be used and the secondary lever arm is accurately entered and doesn't need online re-estimation.
      secondaryLeverMode: 3

      # 0 Measurement is not taken into account
      # 1 Measurement is rejected if inconsistent with current estimate (depending on error model)
      # 2 Measurement is always accepted
      posRejectMode: 1
      velRejectMode: 1
      hdtRejectMode: 1

    # Odometer configuration
    odom:
      # Odometer's gain Pulses/m
      gain: 4800.0
      # User gain average error (%)
      gain_error: 0
      # Odometer's direction
      # false: positive
      # true: negative
      direction: false

      # Odometer lever arm in IMU X axis (m)
      leverArmX: 0.0
      leverArmY: 0.0
      leverArmZ: 0.0

      # Odometer rejection mode
      # 0 Measurement is not taken into account
      # 1 Measurement is rejected if inconsistent with current estimate (depending on error model)
      # 2 Measurement is always accepted
      rejectMode: 0

    ############################### Output configuration ###############################
    # 0 Output is disabled
    # 1 Output is generated at 200Hz
    # 2 Output is generated at 100Hz
    # 4 Output is generated at 50Hz
    # 8 Output is generated at 25Hz
    # 10 Output is generated at 20Hz
    # 20 Output is generated at 10Hz
    # 40 Output is generated at 5Hz
    # 200 Output is generated at 1Hz
    # 10000 Pulse Per Second. Same mode as above.
    # 10001 Output sent when a new data is available.
    # 10002 Output is generated when a new virtual odometer event occurs
    # 10003 Output is generated on a Sync In A event
    # 10004 Output is generated on a Sync In B event
    # 10005 Output is generated on a Sync In C event
    # 10006 Output is generated on a Sync In D event
    output:
      time_reference: ros

      # Ros standard output:
      # Note: If true publish ROS standard messages.
      ros_standard: true
      # Frame convention:
      # Note: If true messages are expressed in the ENU convention.
      #
      # true : ENU convention (X east, Y north, Z up)
      # false (default): NED convention (X north, Y east, Z down)
      use_enu: true

      # Frame ID:
      # Note: If the frame convention is NED so the default frame ID is (imu_link_ned)
      #       else if the convention is ENU so the default frame ID is (imu_link)
      # frame_id: gnss0

      # Status general, clock, com aiding, solution, heave
      log_status: 200
      # Includes IMU status, acc., gyro, temp delta speeds and delta angles values
      log_imu_data: 8
      # Includes roll, pitch, yaw and their accuracies on each axis
      log_ekf_euler: 8
      # Includes the 4 quaternions values
      # ! 2025-08-15: I don't know if below applies anymoreS
      # ! EKF_QUAT MUST BE OFF TO GET CORRECT ORIENTATION FOR imu/odometry
      # ! AS ERROR IN DRIVER, HOWEVER THIS WILL ALSO DISABLE imu/data
      log_ekf_quat: 8
      # Position and velocities in NED coordinates with the accuracies on each axis
      log_ekf_nav: 10001
      # Heave, surge and sway and accelerations on each axis for up to 4 points
      log_ship_motion: 0
      # Provides UTC time reference
      log_utc_time: 0
      # Magnetic data with associated accelerometer on each axis
      log_mag: 10
      # Magnetometer calibration data (raw buffer)
      log_mag_calib: 0
      # GPS velocities from primary or secondary GPS receiver
      log_gps1_vel: 10001
      # GPS positions from primary or secondary GPS receiver
      log_gps1_pos: 10001
      # GPS true heading from dual antenna system
      log_gps1_hdt: 10001
      # GPS 1 raw data for post processing.
      log_gps1_raw: 0
      # Provides odometer velocity
      log_odo_vel: 0
      # Event A/B/C/D Event markers sent when events are detected on a sync in pin
      log_event_a: 0
      log_event_b: 0
      log_event_c: 0
      log_event_d: 0
      # Air data
      log_air_data: 0
      # Short IMU data
      log_imu_short: 0